### ISSUE TITLE
Possible race condition when reading expired item

### ISSUE THREAD

**Issue by anth12** [StefH/DistributedCache.AzureTableStorage#19]
I encountered the following error from a call to `DistributedCacheExtensions.GetStringAsync` for a cached item accessed frequently with a short (10s) expiry. 

Looking at the implementation, I suspect there's a race condition in `RefreshAsync` when multiple processes invoke with the same key right before it expires resulting in one removing the cache entry while the other attempts to update the `LastAccessTime`.

One option may be to change `_tableSet.Value.UpdateAsync` to `_tableSet.Value.AddOrUpdateAsync`. This approach would result in recreating an expired item... Alternatively, error handling to catch the Table Storage write failure could be added.

``` 
      Azure.RequestFailedException: The specified resource does not exist.
RequestId:e7c2ea29-73d9-4b2b-a79c-4f1fa27de8a3
Time:2023-06-14T08:24:18.864Z
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound

      Content:
      {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The
specified resource does not exist.\nRequestId:e7c2ea29-73d9-4b2b-a79c-4f1fa27de8a3\nTim
e:2023-06-14T08:24:18.864Z"}}}

      Headers:
      Server: Azurite-Table/3.23.0
      x-ms-error-code: REDACTED
      x-ms-request-id: e7c2ea29-73d9-4b2b-a79c-4f1fa27de8a3
      x-ms-version: REDACTED
      Date: Wed, 14 Jun 2023 08:24:18 GMT
      Connection: keep-alive
      Keep-Alive: REDACTED
      Transfer-Encoding: chunked
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8


         at Azure.Data.Tables.TableRestClient.MergeEntityAsync(String table, String par
titionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntity
Properties, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.UpdateEntityAsync[T](T entity, ETag ifMatch,
TableUpdateMode mode, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.R
efreshAsync(String key, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.G
etAsync(String key, CancellationToken token)
         at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStri
ngAsync(IDistributedCache cache, String key, CancellationToken token)
...

```

**Comment by StefH** [comment]
@anth12 
If you can create a example console which recreates this issue and create a PR, that would be very nice.

**Comment by StefH** [comment]
@anth12 
Any news on this one?

**Comment by StefH** [comment]
@anth12
Any news on this one?

**Comment by anth12** [comment]
Hi @StefH,

Sorry for the slow reply here. We ended up ignoring these errors for a while, and it completely slipped off my radar.

I’ve taken another look and put together a small repro to demonstrate what we’re seeing. The relevant commit is here:
https://github.com/anth12/DistributedCache.AzureTableStorage/commit/9b2f1223269ca00c065812270b74229f3a882985#diff-cc8ff50532d4e68e50ccfb4d36519e1b56b5da3fa703a914e369b5b8ee87b2c5R93-R131

What I’m seeing:
- Everything works fine against the local storage emulator.
- When pointing at a real Azure Table Storage account, it sometimes throws a RequestFailedException with 404 ResourceNotFound.
- It’s not consistent and only seems to happen some of the time.


```
C:/Dev/DistributedCache.AzureTableStorage/src/ConsoleAppExample.V3/bin/Debug/net10.0/ConsoleAppExample.exe
info: ConsoleAppExample.V3.Program[0]
      Start...
fail: ConsoleAppExample.V3.Program[0]
      Exception in GetStringAsync
      Azure.RequestFailedException: The specified resource does not exist.
RequestId:7ffcb682-8002-00b2-711c-743ad8000000
Time:2025-12-23T14:56:17.4910791Z
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound
      
      Content:
      {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:7ffcb682-8002-00b2-711c-743ad8000000\nTime:2025-12-23T14:56:17.4910791Z"}}}
      
      Headers:
      Cache-Control: no-cache
      Transfer-Encoding: chunked
      Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
      x-ms-request-id: 7ffcb682-8002-00b2-711c-743ad8000000
      x-ms-client-request-id: f5523646-ac42-4922-b66a-f5bff42df274
      x-ms-version: REDACTED
      X-Content-Type-Options: REDACTED
      Date: Tue, 23 Dec 2025 14:56:17 GMT
      Server-Timing: REDACTED
      Cf-Team: REDACTED
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
      
         at Azure.Data.Tables.TableRestClient.MergeEntityAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.UpdateEntityAsync[T](T entity, ETag ifMatch, TableUpdateMode mode, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.RefreshAsync(String key, CancellationToken cancellationToken) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 116
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.GetAsync(String key, CancellationToken token) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 79
         at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
         at ConsoleAppExample.V3.Program.<>c__DisplayClass2_1.<<ReproduceRaceCondition>b__0>d.MoveNext() in C:\Dev\DistributedCache.AzureTableStorage\src\ConsoleAppExample.V3\Program.cs:line 115
fail: ConsoleAppExample.V3.Program[0]
      Exception in GetStringAsync
      Azure.RequestFailedException: The specified resource does not exist.
RequestId:52930ffb-e002-00f9-171c-74c68b000000
Time:2025-12-23T14:56:17.4900269Z
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound
      
      Content:
      {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:52930ffb-e002-00f9-171c-74c68b000000\nTime:2025-12-23T14:56:17.4900269Z"}}}
      
      Headers:
      Cache-Control: no-cache
      Transfer-Encoding: chunked
      Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
      x-ms-request-id: 52930ffb-e002-00f9-171c-74c68b000000
      x-ms-client-request-id: 01979dd1-a21f-44cb-b996-0fe43ad28b99
      x-ms-version: REDACTED
      X-Content-Type-Options: REDACTED
      Date: Tue, 23 Dec 2025 14:56:16 GMT
      Server-Timing: REDACTED
      Cf-Team: REDACTED
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
      
         at Azure.Data.Tables.TableRestClient.MergeEntityAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.UpdateEntityAsync[T](T entity, ETag ifMatch, TableUpdateMode mode, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.RefreshAsync(String key, CancellationToken cancellationToken) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 116
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.GetAsync(String key, CancellationToken token) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 79
         at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
         at ConsoleAppExample.V3.Program.<>c__DisplayClass2_1.<<ReproduceRaceCondition>b__0>d.MoveNext() in C:\Dev\DistributedCache.AzureTableStorage\src\ConsoleAppExample.V3\Program.cs:line 115
fail: ConsoleAppExample.V3.Program[0]
      Exception in GetStringAsync
      Azure.RequestFailedException: The specified resource does not exist.
RequestId:9c202e12-d002-0074-7c1c-74f159000000
Time:2025-12-23T14:56:17.4911857Z
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound
      
      Content:
      {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:9c202e12-d002-0074-7c1c-74f159000000\nTime:2025-12-23T14:56:17.4911857Z"}}}
      
      Headers:
      Cache-Control: no-cache
      Transfer-Encoding: chunked
      Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
      x-ms-request-id: 9c202e12-d002-0074-7c1c-74f159000000
      x-ms-client-request-id: 9fab049a-c2b5-4817-8193-08f8cdeaf5d3
      x-ms-version: REDACTED
      X-Content-Type-Options: REDACTED
      Date: Tue, 23 Dec 2025 14:56:17 GMT
      Server-Timing: REDACTED
      Cf-Team: REDACTED
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
      
         at Azure.Data.Tables.TableRestClient.MergeEntityAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.UpdateEntityAsync[T](T entity, ETag ifMatch, TableUpdateMode mode, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.RefreshAsync(String key, CancellationToken cancellationToken) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 116
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.GetAsync(String key, CancellationToken token) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 79
         at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
         at ConsoleAppExample.V3.Program.<>c__DisplayClass2_1.<<ReproduceRaceCondition>b__0>d.MoveNext() in C:\Dev\DistributedCache.AzureTableStorage\src\ConsoleAppExample.V3\Program.cs:line 115
fail: ConsoleAppExample.V3.Program[0]
      Exception in GetStringAsync
      Azure.RequestFailedException: The specified resource does not exist.
RequestId:97db3bf6-9002-00e3-331c-74a754000000
Time:2025-12-23T14:56:17.4908977Z
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound
      
      Content:
      {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:97db3bf6-9002-00e3-331c-74a754000000\nTime:2025-12-23T14:56:17.4908977Z"}}}
      
      Headers:
      Cache-Control: no-cache
      Transfer-Encoding: chunked
      Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
      x-ms-request-id: 97db3bf6-9002-00e3-331c-74a754000000
      x-ms-client-request-id: 1baf0ac4-8a50-418b-91e3-5bea8b432616
      x-ms-version: REDACTED
      X-Content-Type-Options: REDACTED
      Date: Tue, 23 Dec 2025 14:56:17 GMT
      Server-Timing: REDACTED
      Cf-Team: REDACTED
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
      
         at Azure.Data.Tables.TableRestClient.MergeEntityAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.UpdateEntityAsync[T](T entity, ETag ifMatch, TableUpdateMode mode, CancellationToken cancellationToken)
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.RefreshAsync(String key, CancellationToken cancellationToken) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 116
         at DistributedCache.AzureTableStorage.Implementations.AzureTableStorageCache.GetAsync(String key, CancellationToken token) in C:\Dev\DistributedCache.AzureTableStorage\src\DistributedCache.AzureTableStorage.V3\Implementations\AzureTableStorageCache.cs:line 79
         at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
         at ConsoleAppExample.V3.Program.<>c__DisplayClass2_1.<<ReproduceRaceCondition>b__0>d.MoveNext() in C:\Dev\DistributedCache.AzureTableStorage\src\ConsoleAppExample.V3\Program.cs:line 115
info: ConsoleAppExample.V3.Program[0]
      Race condition test completed.

Process finished with exit code 0.
```

I'll look into possible fixes.

Thanks,
Anthony
